/*
 * $Id: sunWin.java,v 1.9 2010/01/30 21:39:17 fc Exp $
 *
 * JStars is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * JStars is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 * 
 * Copyright (c) 2003 Florent Charpin
 * 
 * email: jstars@florent.us
 *
 *
 */

package jstars.gui;

/**
 *
 * @author  florent Charpin
 */


import java.awt.Color;


public class sunWin extends javax.swing.JFrame {
    
    
    protected class JsunPanel extends javax.swing.JPanel {
        
        java.awt.GradientPaint gp;
        Color color = new Color(240,234,185);
        @Override
        public void paintComponent(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
            int w = getWidth();
            int h = getHeight();
            gp = new java.awt.GradientPaint(0,0, color, w,h, Color.white, true);
            g2.setPaint(gp);
            g2.fillRect(0, 0, w, h);
        }
        @Override
        public boolean isOpaque() {
            return true;
        }
        
    }
    
    jstars.util.Jsun TheSun;
    javax.swing.JToggleButton sunButton;
    
    /** Creates new form sunWin */
    public sunWin(jstars.util.Jsun _sun, javax.swing.JToggleButton Button) {
        TheSun = _sun;
        sunButton = Button;
        initComponents();
    }
    
//    public void paintComponents(java.awt.Graphics g) {
//        int w = getWidth();
//        int h = getHeight();
//        int leftW = w / 2;
//        int topH = h / 2;
//        
//        // Paint the top left and bottom right in red.
//        g.setColor(Color.red);
//        g.fillRect(0, 0, leftW, topH);
//        g.fillRect(leftW, topH, w - leftW, h - topH);
//        
//        // Paint the bottom left and top right in white.
//        g.setColor(Color.white);
//        g.fillRect(0, topH, leftW, h - topH);
//        g.fillRect(leftW, 0, w - leftW, topH);
//        
//        System.out.println("ZZZZZ");
//        //super.paintComponents(g);
//    }
//    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new JsunPanel();
        jLabel1 = new javax.swing.JLabel();
        RALabel = new javax.swing.JLabel();
        RAValue = new javax.swing.JLabel();
        decValue = new javax.swing.JLabel();
        DecLabel = new javax.swing.JLabel();
        AzValue = new javax.swing.JLabel();
        AzLabel = new javax.swing.JLabel();
        AltValue = new javax.swing.JLabel();
        AltLabel = new javax.swing.JLabel();
        TimeModeLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        riseValue = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        setValue = new javax.swing.JLabel();
        AltValue3 = new javax.swing.JLabel();
        riseAZ = new javax.swing.JLabel();
        AltValue5 = new javax.swing.JLabel();
        AltValue6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        transValue = new javax.swing.JLabel();
        AltValue8 = new javax.swing.JLabel();
        AltValue9 = new javax.swing.JLabel();
        twilightPanel = new javax.swing.JPanel();
        dawn6 = new javax.swing.JLabel();
        dawnLabel = new javax.swing.JLabel();
        duskLabel = new javax.swing.JLabel();
        civilLabel = new javax.swing.JLabel();
        dusk6 = new javax.swing.JLabel();
        nautLabel = new javax.swing.JLabel();
        dawn12 = new javax.swing.JLabel();
        dusk12 = new javax.swing.JLabel();
        astroLabel = new javax.swing.JLabel();
        dawn18 = new javax.swing.JLabel();
        dusk18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        distValue = new javax.swing.JLabel();
        distLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sun");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/jstars/images/sun.gif"))
        );
        setName("sunFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mainPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sun");
        jLabel1.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 15, 5);
        mainPanel.add(jLabel1, gridBagConstraints);

        RALabel.setFont(new java.awt.Font("Dialog", 0, 12));
        RALabel.setText("RA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 8);
        mainPanel.add(RALabel, gridBagConstraints);

        RAValue.setFont(new java.awt.Font("Dialog", 0, 12));
        RAValue.setText("00:00:00.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPanel.add(RAValue, gridBagConstraints);

        decValue.setFont(new java.awt.Font("Dialog", 0, 12));
        decValue.setText("00:00:00.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        mainPanel.add(decValue, gridBagConstraints);

        DecLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        DecLabel.setText("Dec:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 8);
        mainPanel.add(DecLabel, gridBagConstraints);

        AzValue.setFont(new java.awt.Font("Dialog", 0, 12));
        AzValue.setText("00:00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPanel.add(AzValue, gridBagConstraints);

        AzLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        AzLabel.setText("Azimuth:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 8);
        mainPanel.add(AzLabel, gridBagConstraints);

        AltValue.setFont(new java.awt.Font("Dialog", 0, 12));
        AltValue.setText("00:00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 10);
        mainPanel.add(AltValue, gridBagConstraints);

        AltLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        AltLabel.setText("Altitude");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 7, 8);
        mainPanel.add(AltLabel, gridBagConstraints);

        TimeModeLabel.setFont(new java.awt.Font("Dialog", 0, 10));
        TimeModeLabel.setText("Time Mode: UTC");
        TimeModeLabel.setBorder(new javax.swing.border.EtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        mainPanel.add(TimeModeLabel, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel11.setText("Rise:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 8);
        mainPanel.add(jLabel11, gridBagConstraints);

        riseValue.setFont(new java.awt.Font("Dialog", 0, 12));
        riseValue.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPanel.add(riseValue, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel12.setText("Set:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 8);
        mainPanel.add(jLabel12, gridBagConstraints);

        setValue.setFont(new java.awt.Font("Dialog", 0, 12));
        setValue.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        mainPanel.add(setValue, gridBagConstraints);

        AltValue3.setFont(new java.awt.Font("Dialog", 0, 12));
        AltValue3.setText("Az:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        mainPanel.add(AltValue3, gridBagConstraints);

        riseAZ.setFont(new java.awt.Font("Dialog", 0, 12));
        riseAZ.setText("000:00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        mainPanel.add(riseAZ, gridBagConstraints);

        AltValue5.setFont(new java.awt.Font("Dialog", 0, 12));
        AltValue5.setText("Az:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        mainPanel.add(AltValue5, gridBagConstraints);

        AltValue6.setFont(new java.awt.Font("Dialog", 0, 12));
        AltValue6.setText("000:00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        mainPanel.add(AltValue6, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel13.setText("Transit:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 8);
        mainPanel.add(jLabel13, gridBagConstraints);

        transValue.setFont(new java.awt.Font("Dialog", 0, 12));
        transValue.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 10);
        mainPanel.add(transValue, gridBagConstraints);

        AltValue8.setFont(new java.awt.Font("Dialog", 0, 12));
        AltValue8.setText("Alt:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 3);
        mainPanel.add(AltValue8, gridBagConstraints);

        AltValue9.setFont(new java.awt.Font("Dialog", 0, 12));
        AltValue9.setText("+00:00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        mainPanel.add(AltValue9, gridBagConstraints);

        twilightPanel.setLayout(new java.awt.GridBagLayout());

        twilightPanel.setOpaque(false);
        dawn6.setFont(new java.awt.Font("Dialog", 0, 12));
        dawn6.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        twilightPanel.add(dawn6, gridBagConstraints);

        dawnLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        dawnLabel.setText("Dawn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        twilightPanel.add(dawnLabel, gridBagConstraints);

        duskLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        duskLabel.setText("Dusk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        twilightPanel.add(duskLabel, gridBagConstraints);

        civilLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        civilLabel.setText("Civil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        twilightPanel.add(civilLabel, gridBagConstraints);

        dusk6.setFont(new java.awt.Font("Dialog", 0, 12));
        dusk6.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        twilightPanel.add(dusk6, gridBagConstraints);

        nautLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nautLabel.setText("Nautical");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        twilightPanel.add(nautLabel, gridBagConstraints);

        dawn12.setFont(new java.awt.Font("Dialog", 0, 12));
        dawn12.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        twilightPanel.add(dawn12, gridBagConstraints);

        dusk12.setFont(new java.awt.Font("Dialog", 0, 12));
        dusk12.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        twilightPanel.add(dusk12, gridBagConstraints);

        astroLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        astroLabel.setText("Astonomical");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        twilightPanel.add(astroLabel, gridBagConstraints);

        dawn18.setFont(new java.awt.Font("Dialog", 0, 12));
        dawn18.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        twilightPanel.add(dawn18, gridBagConstraints);

        dusk18.setFont(new java.awt.Font("Dialog", 0, 12));
        dusk18.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weightx = 1.0;
        twilightPanel.add(dusk18, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel22.setText("Twilights:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        twilightPanel.add(jLabel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        mainPanel.add(twilightPanel, gridBagConstraints);

        distValue.setFont(new java.awt.Font("Dialog", 0, 12));
        distValue.setText("1.0000 ua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 7, 10);
        mainPanel.add(distValue, gridBagConstraints);

        distLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        distLabel.setText("Distance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 7, 8);
        mainPanel.add(distLabel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });

        jMenu1.add(closeMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents
    
    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        sunButton.setSelected(false);
        dispose();
    }//GEN-LAST:event_closeMenuItemActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        sunButton.setSelected(false);
        dispose();
    }//GEN-LAST:event_exitForm
    
    void updateDisp() {
        RAValue.setText(TheSun.getRAString());
        decValue.setText(TheSun.getDecString());
        AltValue.setText(TheSun.getAltString());
        AzValue.setText(TheSun.getAzString());
        riseValue.setText(TheSun.riseTimeString());
        setValue.setText(TheSun.setTimeString());
        transValue.setText(TheSun.transTimeString());
        String tt[] = TheSun.getTwilightTime(-6, false);
        dawn6.setText(tt[0]);
        dusk6.setText(tt[1]);
        tt = TheSun.getTwilightTime(-12, false);
        dawn12.setText(tt[0]);
        dusk12.setText(tt[1]);
        tt = TheSun.getTwilightTime(-18, false);
        dawn18.setText(tt[0]);
        dusk18.setText(tt[1]);
        riseAZ.setText(TheSun.getRiseAzString());
        AltValue6.setText(TheSun.getSetAzString());
        AltValue9.setText(TheSun.getTransAltString());
        distValue.setText(TheSun.getEarthDistanceString());
        //sundraw.repaint();
    }
    
    public void SetTimeMode(String disp) {
        TimeModeLabel.setText("Time Zone: " + disp);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltLabel;
    private javax.swing.JLabel AltValue;
    private javax.swing.JLabel AltValue3;
    private javax.swing.JLabel AltValue5;
    private javax.swing.JLabel AltValue6;
    private javax.swing.JLabel AltValue8;
    private javax.swing.JLabel AltValue9;
    private javax.swing.JLabel AzLabel;
    private javax.swing.JLabel AzValue;
    private javax.swing.JLabel DecLabel;
    private javax.swing.JLabel RALabel;
    private javax.swing.JLabel RAValue;
    private javax.swing.JLabel TimeModeLabel;
    private javax.swing.JLabel astroLabel;
    private javax.swing.JLabel civilLabel;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JLabel dawn12;
    private javax.swing.JLabel dawn18;
    private javax.swing.JLabel dawn6;
    private javax.swing.JLabel dawnLabel;
    private javax.swing.JLabel decValue;
    private javax.swing.JLabel distLabel;
    private javax.swing.JLabel distValue;
    private javax.swing.JLabel dusk12;
    private javax.swing.JLabel dusk18;
    private javax.swing.JLabel dusk6;
    private javax.swing.JLabel duskLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nautLabel;
    private javax.swing.JLabel riseAZ;
    private javax.swing.JLabel riseValue;
    private javax.swing.JLabel setValue;
    private javax.swing.JLabel transValue;
    private javax.swing.JPanel twilightPanel;
    // End of variables declaration//GEN-END:variables
    
}
